### ISSUE TITLE
Security checklist

### ISSUE THREAD

**Issue by simongray** [kuhumcst/glossematics#23]
e.g. https://observatory.mozilla.org/analyze/glossematics.org

**Comment by simongray** [comment]
https://github.com/rm-hull/nvd-clojure

**Comment by simongray** [comment]
Also,  should typical investigate typical Docker security advice, e.g. not running the container as root.

**Comment by simongray** [comment]
Docker checklist update
----
> https://cloudberry.engineering/article/dockerfile-security-best-practices/

- [x]  1. Do not store secrets in environment variables
  - The only secrets in use are certificates which are stored on disk.
- [x] 2. Only use trusted base images
- [ ] 3. Do not use ‘latest’ tag for base image
  - I need to change this to specific versions for both Dockerfiles in use.
- [x] 4. Avoid curl bashing
  - This is only  done in a **single** case (installing Clojure) since it is the officially advertised way to do so.
- [x] 5. Do not upgrade your system packages
- [x] 6. Do not use ADD if possible
- [ ] 7. Do not root
- [x] 8. Do not sudo

In conclusion:

* I should fix a specific version for both Glossematics and nginx-reverse-proxy.
* I should use a privileged Docker-specific user instead of root + research more the permissions issue more thoroughly.

**Comment by simongray** [comment]
nvd-clojure report
----

It doesn't look too good...

I will have to look into this now.

```
+-----------------------------------------------------------------------------+------------------------------------------------------------------------------+
| dependency                                                                  | status                                                                       |
+-----------------------------------------------------------------------------+------------------------------------------------------------------------------+
| aws-java-sdk-core-1.11.713.jar                                              | CVE-2022-31159                                                               |
| bcprov-jdk15on-1.64.jar                                                     | CVE-2020-0187, CVE-2020-15522                                                |
| cljs-priority-map-1.2.1.jar                                                 | CVE-2022-23173, CVE-2022-23172                                               |
| closure-compiler-unshaded-v20220601.jar/META-INF/maven/com.google.code.g... | CVE-2022-25647                                                               |
| commons-collections-3.2.1.jar                                               | CVE-2015-6420                                                                |
| commons-compress-1.19.jar                                                   | CVE-2021-36090, CVE-2021-35515, CVE-2021-35516, CVE-2021-35517               |
| data.priority-map-1.1.0.jar                                                 | CVE-2022-23173, CVE-2022-23172                                               |
| google-closure-library-0.0-20211011-0726fdeb.jar                            | CVE-2020-8910                                                                |
| http2-common-9.4.44.v20210927.jar                                           | CVE-2022-2048, CVE-2022-2047                                                 |
| http2-server-9.4.44.v20210927.jar                                           | CVE-2022-2048, CVE-2022-2047                                                 |
| jackson-databind-2.13.2.2.jar                                               | CVE-2022-42004, CVE-2022-42003                                               |
| jackson-dataformat-cbor-2.9.9.jar                                           | CVE-2020-28491                                                               |
| jetty-io-9.4.44.v20210927.jar                                               | CVE-2022-2048, CVE-2022-2047                                                 |
| jetty-server-9.4.44.v20210927.jar                                           | CVE-2022-2048, CVE-2022-2047                                                 |
| jmespath-java-1.11.713.jar                                                  | CVE-2022-31159                                                               |
| jsoup-1.12.1.jar                                                            | CVE-2022-36033, CVE-2021-37714                                               |
| logback-core-1.0.12.jar                                                     | CVE-2021-42550, CVE-2017-5929                                                |
| poi-4.1.1.jar                                                               | CVE-2022-26336                                                               |
| undertow-core-2.2.4.Final.jar                                               | CVE-2022-1319, CVE-2022-2053, CVE-2021... |
| velocity-1.7.jar                                                            | CVE-2020-13936                                                               |
| websocket-client-9.4.44.v20210927.jar                                       | CVE-2022-2048, CVE-2022-2047                                                 |
| websocket-server-9.4.44.v20210927.jar                                       | CVE-2022-2048, CVE-2022-2047                                                 |
| xnio-api-3.8.0.Final.jar                                                    | CVE-2022-0084, CVE-2020-14340                                                |
+-----------------------------------------------------------------------------+------------------------------------------------------------------------------+

47 vulnerabilities detected. Severity: HIGH

```

**Comment by simongray** [comment]
Current picture as of 9f358ed2bbc7ee13b71f1d9ef2782aa05df9ad5c

<img width="1787" alt="Skærmbillede 2022-11-11 kl  14 10 13" src="https://user-images.githubusercontent.com/1388652/201347252-4014c5ab-1791-4268-9078-33a87d50d1f2.png">

I can't locate logback, undertow, or xnio in the deps tree, unfortunately. Unsure why. The velocity stuff is a transitive dependency of opensaml which is already at the latest version, so...

I think this is the bet I can do for now.

**Comment by simongray** [comment]
https://github.com/clj-holmes/clj-watson was recommended by both Alex Miller and Sean Corfield.

**Comment by simongray** [comment]
I will consider this fixed as of b77361a92199df7fa3f71070f742aed1bcb5abdb

I have tried and failed at making the nginx certbot container run as a non-root user, but from what I can tell it isn't an issue since nginx apparently spawns its own user which it runs the server process with. The Glossematics container creates a new user especially for itself.
